[build]
  command = "eleventy"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/latest"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/latest"
  status = 301
  force = true
